package com.myspace.eyeone;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String IC;

	private java.lang.Boolean red_eye;

	private java.lang.Boolean eye_pain;

	private java.lang.Boolean circumciliary_injection;

	private java.lang.Boolean headache;

	private java.lang.Boolean eye_itch;

	private java.lang.Boolean eyelid_swelling;

	private java.lang.Boolean tearing;

	private java.lang.Boolean blurred_vision;

	private java.lang.Boolean metamorphopsia;

	private java.lang.Boolean floaters;

	private java.lang.Boolean photopsia;

	private java.lang.Boolean itch_redness;

	private java.lang.Boolean improves_with_lubricants;

	private java.lang.Boolean resolves_with_lubricants;

	private java.lang.Boolean tears_roll_down_cheek;

	private java.lang.Boolean improves_with_pinhole;

	private java.lang.Boolean has_diabetes;

	private java.lang.Boolean wears_contact_lens;

	private java.lang.Boolean trauma;

	private java.lang.Boolean unilateral;

	private java.lang.Boolean bilateral;

	private java.lang.Boolean cornea_FB_seen;

	private java.lang.Boolean reduced_red_reflex;

	private java.lang.Boolean white_spot_on_cornea;

	private java.lang.Boolean RAPD;

	private java.lang.Boolean mid_dilated_pupils;

	private java.lang.String diagnosis;

	private String diagNum;

	public BusinessObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getIC() {
		return this.IC;
	}

	public void setIC(java.lang.String IC) {
		this.IC = IC;
	}

	public java.lang.Boolean getRed_eye() {
		return this.red_eye;
	}

	public void setRed_eye(java.lang.Boolean red_eye) {
		this.red_eye = red_eye;
	}

	public java.lang.Boolean getEye_pain() {
		return this.eye_pain;
	}

	public void setEye_pain(java.lang.Boolean eye_pain) {
		this.eye_pain = eye_pain;
	}

	public java.lang.Boolean getCircumciliary_injection() {
		return this.circumciliary_injection;
	}

	public void setCircumciliary_injection(
			java.lang.Boolean circumciliary_injection) {
		this.circumciliary_injection = circumciliary_injection;
	}

	public java.lang.Boolean getHeadache() {
		return this.headache;
	}

	public void setHeadache(java.lang.Boolean headache) {
		this.headache = headache;
	}

	public java.lang.Boolean getEye_itch() {
		return this.eye_itch;
	}

	public void setEye_itch(java.lang.Boolean eye_itch) {
		this.eye_itch = eye_itch;
	}

	public java.lang.Boolean getEyelid_swelling() {
		return this.eyelid_swelling;
	}

	public void setEyelid_swelling(java.lang.Boolean eyelid_swelling) {
		this.eyelid_swelling = eyelid_swelling;
	}

	public java.lang.Boolean getTearing() {
		return this.tearing;
	}

	public void setTearing(java.lang.Boolean tearing) {
		this.tearing = tearing;
	}

	public java.lang.Boolean getBlurred_vision() {
		return this.blurred_vision;
	}

	public void setBlurred_vision(java.lang.Boolean blurred_vision) {
		this.blurred_vision = blurred_vision;
	}

	public java.lang.Boolean getMetamorphopsia() {
		return this.metamorphopsia;
	}

	public void setMetamorphopsia(java.lang.Boolean metamorphopsia) {
		this.metamorphopsia = metamorphopsia;
	}

	public java.lang.Boolean getFloaters() {
		return this.floaters;
	}

	public void setFloaters(java.lang.Boolean floaters) {
		this.floaters = floaters;
	}

	public java.lang.Boolean getPhotopsia() {
		return this.photopsia;
	}

	public void setPhotopsia(java.lang.Boolean photopsia) {
		this.photopsia = photopsia;
	}

	public java.lang.Boolean getItch_redness() {
		return this.itch_redness;
	}

	public void setItch_redness(java.lang.Boolean itch_redness) {
		this.itch_redness = itch_redness;
	}

	public java.lang.Boolean getImproves_with_lubricants() {
		return this.improves_with_lubricants;
	}

	public void setImproves_with_lubricants(
			java.lang.Boolean improves_with_lubricants) {
		this.improves_with_lubricants = improves_with_lubricants;
	}

	public java.lang.Boolean getResolves_with_lubricants() {
		return this.resolves_with_lubricants;
	}

	public void setResolves_with_lubricants(
			java.lang.Boolean resolves_with_lubricants) {
		this.resolves_with_lubricants = resolves_with_lubricants;
	}

	public java.lang.Boolean getTears_roll_down_cheek() {
		return this.tears_roll_down_cheek;
	}

	public void setTears_roll_down_cheek(java.lang.Boolean tears_roll_down_cheek) {
		this.tears_roll_down_cheek = tears_roll_down_cheek;
	}

	public java.lang.Boolean getImproves_with_pinhole() {
		return this.improves_with_pinhole;
	}

	public void setImproves_with_pinhole(java.lang.Boolean improves_with_pinhole) {
		this.improves_with_pinhole = improves_with_pinhole;
	}

	public java.lang.Boolean getHas_diabetes() {
		return this.has_diabetes;
	}

	public void setHas_diabetes(java.lang.Boolean has_diabetes) {
		this.has_diabetes = has_diabetes;
	}

	public java.lang.Boolean getWears_contact_lens() {
		return this.wears_contact_lens;
	}

	public void setWears_contact_lens(java.lang.Boolean wears_contact_lens) {
		this.wears_contact_lens = wears_contact_lens;
	}

	public java.lang.Boolean getTrauma() {
		return this.trauma;
	}

	public void setTrauma(java.lang.Boolean trauma) {
		this.trauma = trauma;
	}

	public java.lang.Boolean getUnilateral() {
		return this.unilateral;
	}

	public void setUnilateral(java.lang.Boolean unilateral) {
		this.unilateral = unilateral;
	}

	public java.lang.Boolean getBilateral() {
		return this.bilateral;
	}

	public void setBilateral(java.lang.Boolean bilateral) {
		this.bilateral = bilateral;
	}

	public java.lang.Boolean getCornea_FB_seen() {
		return this.cornea_FB_seen;
	}

	public void setCornea_FB_seen(java.lang.Boolean cornea_FB_seen) {
		this.cornea_FB_seen = cornea_FB_seen;
	}

	public java.lang.Boolean getReduced_red_reflex() {
		return this.reduced_red_reflex;
	}

	public void setReduced_red_reflex(java.lang.Boolean reduced_red_reflex) {
		this.reduced_red_reflex = reduced_red_reflex;
	}

	public java.lang.Boolean getWhite_spot_on_cornea() {
		return this.white_spot_on_cornea;
	}

	public void setWhite_spot_on_cornea(java.lang.Boolean white_spot_on_cornea) {
		this.white_spot_on_cornea = white_spot_on_cornea;
	}

	public java.lang.Boolean getRAPD() {
		return this.RAPD;
	}

	public void setRAPD(java.lang.Boolean RAPD) {
		this.RAPD = RAPD;
	}

	public java.lang.Boolean getMid_dilated_pupils() {
		return this.mid_dilated_pupils;
	}

	public void setMid_dilated_pupils(java.lang.Boolean mid_dilated_pupils) {
		this.mid_dilated_pupils = mid_dilated_pupils;
	}

	public java.lang.String getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(java.lang.String diagnosis) {
		this.diagnosis = diagnosis;
	}

	public java.lang.String getDiagNum() {
		return this.diagNum;
	}

	public void setDiagNum(java.lang.String diagNum) {
		this.diagNum = diagNum;
	}

	public BusinessObject(java.lang.String name, java.lang.String IC,
			java.lang.Boolean red_eye, java.lang.Boolean eye_pain,
			java.lang.Boolean circumciliary_injection,
			java.lang.Boolean headache, java.lang.Boolean eye_itch,
			java.lang.Boolean eyelid_swelling, java.lang.Boolean tearing,
			java.lang.Boolean blurred_vision, java.lang.Boolean metamorphopsia,
			java.lang.Boolean floaters, java.lang.Boolean photopsia,
			java.lang.Boolean itch_redness,
			java.lang.Boolean improves_with_lubricants,
			java.lang.Boolean resolves_with_lubricants,
			java.lang.Boolean tears_roll_down_cheek,
			java.lang.Boolean improves_with_pinhole,
			java.lang.Boolean has_diabetes,
			java.lang.Boolean wears_contact_lens, java.lang.Boolean trauma,
			java.lang.Boolean unilateral, java.lang.Boolean bilateral,
			java.lang.Boolean cornea_FB_seen,
			java.lang.Boolean reduced_red_reflex,
			java.lang.Boolean white_spot_on_cornea, java.lang.Boolean RAPD,
			java.lang.Boolean mid_dilated_pupils, java.lang.String diagnosis,
			java.lang.String diagNum) {
		this.name = name;
		this.IC = IC;
		this.red_eye = red_eye;
		this.eye_pain = eye_pain;
		this.circumciliary_injection = circumciliary_injection;
		this.headache = headache;
		this.eye_itch = eye_itch;
		this.eyelid_swelling = eyelid_swelling;
		this.tearing = tearing;
		this.blurred_vision = blurred_vision;
		this.metamorphopsia = metamorphopsia;
		this.floaters = floaters;
		this.photopsia = photopsia;
		this.itch_redness = itch_redness;
		this.improves_with_lubricants = improves_with_lubricants;
		this.resolves_with_lubricants = resolves_with_lubricants;
		this.tears_roll_down_cheek = tears_roll_down_cheek;
		this.improves_with_pinhole = improves_with_pinhole;
		this.has_diabetes = has_diabetes;
		this.wears_contact_lens = wears_contact_lens;
		this.trauma = trauma;
		this.unilateral = unilateral;
		this.bilateral = bilateral;
		this.cornea_FB_seen = cornea_FB_seen;
		this.reduced_red_reflex = reduced_red_reflex;
		this.white_spot_on_cornea = white_spot_on_cornea;
		this.RAPD = RAPD;
		this.mid_dilated_pupils = mid_dilated_pupils;
		this.diagnosis = diagnosis;
		this.diagNum = diagNum;
	}

}